services:
  - type: web
    name: brainblog-backend
    env: node
    buildCommand: cd server && chmod +x build.sh && ./build.sh
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 